services:
  db:
    container_name: db
    image: postgres:17
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpass
      - POSTGRES_DB=dbname

  backend:
    container_name: backend
    build:
      context: .
    ports:
      - 4000:8000
    environment:
      - SECRET_KEY=changeme
      - SQLALCHEMY_DATABASE_URL=postgresql+asyncpg://dbuser:dbpass@db:5432/dbname
    depends_on:
      - db
